config/routes.rb
require 'api_constraints'
require 'subdomain'

Fustal::Application.routes.draw do
  wiki_root '/wiki'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { 
    :registrations => "registrations", :sessions => "sessions", 
    :passwords => "passwords", :omniauth_callbacks => "omniauth_callbacks" 
  }

  namespace :blog, path: '/blog' do
    get "find", to: "posts#find_posts", as: "find_posts"
    get "diskusi", to: "posts#discussion_room", as: "discussion"
    resources :posts do
    end
    get '' => "posts#index"
  end

# New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get "avatar"
      put "remove_avatar"
    end    
  end

  scope module: 'trading' do
    resources :tenders do
      member do
        get "discuss"
      end
      resources :bids
    end
  end

  resources :documents
  resources :houses do
    resources :steps, only: [:show, :update], controller: 'houses/steps'
    resources :tenders, only: [:new, :create], controller: 'trading/tenders'
  end
  resources :comments
  # resources :invoices do
  #   resources :payments
  # end

  # Static Pages
  # root "pages#landing"
  get "home", to: "insides#home", as: :user_root
  get "profil", to: "insides#profile", as: :profile
  get "pilih", to: "insides#choose", as: :choose
  post "/emailconfirmation", to: "insides#email", as: "email_confirmation"
  post "/subscribe", to: "insides#subscribe", as: "subscribe"
  post "/socialize", to: "insides#socialize", as: "socialize"
  get "/simulasi", to: "insides#simulation", as: "simulation"
  get '/change_locale/:locale', to: 'insides#change_locale', as: :change_locale

  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable"
  get "/500" => "errors#internal_server_error"

  namespace :admin do
    root "base#index"
    get 'subscribers', to: "base#subscribers", as: :subscribers
    put 'whitelisting', to: "base#whitelisting", as: :whitelisting
    post 'send_email', to: "base#send_email", as: :send_email
    get 'inbox', to: "base#inbox", as: :inbox
    get 'events', to: "analytics#events", as: :events_analytics
    get 'visits', to: "analytics#visits", as: :visits_analytics
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    resources :posts do
      member do
        put "remove_header"
      end
    end
    resources :documents do
      member do
        get "delete"
      end
    end
    resources :tenders, only: [:index, :edit, :update, :destroy]
    resources :bids, only: [:index, :edit, :update, :destroy]
    resources :houses, skip: [:show]
    resources :comments, skip: [:show]
  end

  # Vanity AB TESTING FRAMEWORK
  get '/vanity' =>'vanity#index'
  get '/vanity/participant/:id' => 'vanity#participant'
  post '/vanity/complete'
  post '/vanity/chooses'
  post '/vanity/reset'
  post '/vanity/add_participant'
  get '/vanity/image'


  get "/id/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'landing'

  resources :users, only: :show, path: '' do
    resources :tenders, only: :show, path: '', controller: 'trading/tenders'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include WannabeBool::Attributes

  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  # validates :subject, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  # acts_as_votable

  belongs_to :commentable, :polymorphic => true
  belongs_to :user # NOTE: Comments belong to a user

  delegate :name, to: :user, prefix: true
  delegate :avatar, to: :user, prefix: true

  store_accessor :details, 
                 :official, :flagged
  attr_wannabe_bool :official, :flagged
  
  cattr_accessor :vouchers do
    ["keluarga", "sahabat", "kolega"]
  end
  
  # Markdown
  before_save :mark_it_down!

  scope :assessments, -> { where(subject: 'kapiten') } 
  scope :user_as_subject, ->(user) { where(commentable: user) } 

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body_html        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

  def author?(user)
    if self.user == user
      return true
    else
      return false
    end
  end


private
  def mark_it_down!
    MarkdownWriter.html_comment(self) unless self.body_md.nil?
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  before_action :set_comment, only: [:edit, :destroy]

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.assign_attributes(user_id: current_user.id)

    if @comment.save
      flash[:notice] = 'Assessment berhasil dibuat'
    else
      flash[:warning] = 'Assessment gagal dibuat'
    end
    redirect_to :back
  end

  def edit
    @type = @comment.commentable.class.name
    @commentable_id = @comment.commentable.id
    @subject = @comment.subject
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to admin_comments_path
      flash[:notice] =  'Komentar berhasil dikoreksi'
    else
      render :edit
    end   
  end

  def destroy
    @comment.delete
    flash[:notice] =  'Komentar berhasil dihapus'
    redirect_to admin_comments_path
  end

private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(
      :commentable, :commentable_id, :commentable_type, 
      :title, :body_md, :body_html, :subject, :parent_id, :user_id      
    )
  end

end

app/controllers/blog/comments_controller.rb
class Blog::CommentsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [
  #   :new, :edit, :create, :update
  # ]
  before_action :set_comment, only: [:edit]

  def new
  	@comment = Comment.new
    @parent = Comment.find(params[:parent_comment])
    @post = @parent.commentable
  end

  def edit
    # @comment = Comment.friendly.find(params[:id])
    @post = Post.friendly.find(params[:post_id])
  end

  def create
	  @comment = Comment.new(comment_params)
	  @comment.user = current_user || "Tamu"
    @post = Post.friendly.find(params[:post_id])
    @comment.commentable = @post

    if @comment.save
      ahoy.track "Posting Comment", title: "#{@comment.user} posted blog comments"
      redirect_to blog_post_path(@post)
      flash[:notice] = 'Komentar berhasil dibuat'
    else
      render :new
    end	
  end

  def update
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.friendly.find(params[:id])

    if @comment.update(comment_params)
      ahoy.track "Updating Comment", title: "Comment no.#{@comment.id} was edited"
      redirect_to blog_post_path(@post)
      flash[:notice] =  'Komentar berhasil dikoreksi'
    else
      render :edit
    end  	
  end


private
  def set_comment
  	@comment = Comment.friendly.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(
  	  :commentable, :commentable_id, :commentable_type, 
      :title, :body_md, :subject, :parent_id
  	)
  end	

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit]

  def new
    @comment = Comment.new 
    # respond_to :js    
  end

  def create
	  @comment = Comment.new(comment_params)

    if @comment.save
      # ahoy.track "Posting Comment", title: "#{@comment.user} commented on #{@comment.commentable.class.name}"
      flash[:notice] = 'Komentar berhasil dibuat'
    else
      flash[:warning] = 'Komentar gagal dibuat'
    end 
      redirect_to :back
  end

  def edit
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to :back
      flash[:notice] =  'Komentar berhasil dikoreksi'
    else
      render :edit
    end  	
  end


private
  def set_comment
  	@comment = Comment.friendly.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(
  	  :commentable, :commentable_id, :commentable_type, 
      :title, :body_md, :body_html, :subject, :parent_id, :user_id
  	)
  end	

end

app/views/admin/comments/_form.html.erb
<%= simple_form_for([:admin, @comment], html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { radio_buttons: :horizontal_radio_and_checkboxes }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, class: "form-control monospaced-control", placeholder: "Title of the comment..." %>
    <%= f.input :body_md, as: :text, input_html: {rows: 10}, class: "form-control monospaced-control", placeholder: "Post content (Markdown format)..." %>
    <%= f.input :commentable_type, :as => "hidden", :input_html => { value: @type } %>
    <%= f.input :commentable_id, :as => "hidden", :input_html => { value: @commentable_id } %>    
  </div>
  <div class="form-actions">
    <%= f.submit "Simpan", class: "btn btn-round btn-success" %>
  </div>



<% end %>
  

app/views/admin/comments/edit.html.erb
<h3>Modify Comment <span class="light"><%=  %></span></h3><hr class="light"></hr>
<div class="col-md-12 col-sm-12 col-xs-12">
  <%= render 'form' %>
</div>

app/views/admin/comments/index.html.erb
<% title("Comments") %>
<h1>Comments <small>Admin</small></h1>

<%= form_tag admin_comments_path, method: 'get', html: {role: "form"} do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "All", admin_comments_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Author</th>
    <th>On</th>
    <th>Subject</th>
    <th>Created At</th>
    <th>Content</th>
    <th></th>
  </tr>

  <% @comments.each do |comment| %>

    <tr>
      <td><%= link_to comment.id, edit_admin_comment_path(comment) %></td>
      <td><%= link_to comment.user.name, admin_user_path(comment.user) %></td>
      <td><%= comment.commentable.class.name %></td>
      <td><%= comment.subject %></td>
      <td><%= comment.created_at.strftime("%Y/%m/%-d") %></td>
      <td><%= sanitize truncate(comment.body_html, length: 150, escape: false)%></td>
      <td><%= link_to "Hapus", admin_comment_path(comment), method: :delete, data: {confirm: 'Kamu yakin mau melanjutkan?', object: 'Penghapusan komentar'} %></td>
    </tr>

  <% end %>

</table>

app/views/admin/comments/new.html.erb
<h3>Buat Assessment <span class="light"><%=  %></span></h3><hr class="light"></hr>
<div class="col-md-12 col-sm-12 col-xs-12">
  <%= render 'form' %>
</div>