config/routes.rb
require 'api_constraints'
require 'subdomain'

Fustal::Application.routes.draw do
  wiki_root '/wiki'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { 
    :registrations => "registrations", :sessions => "sessions", 
    :passwords => "passwords", :omniauth_callbacks => "omniauth_callbacks" 
  }

  namespace :blog, path: '/blog' do
    get "find", to: "posts#find_posts", as: "find_posts"
    get "diskusi", to: "posts#discussion_room", as: "discussion"
    resources :posts do
    end
    get '' => "posts#index"
  end

# New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get "avatar"
      put "remove_avatar"
    end    
  end

  scope module: 'trading' do
    resources :tenders do
      member do
        get "discuss"
      end
      resources :bids
    end
  end

  resources :documents
  resources :houses do
    resources :steps, only: [:show, :update], controller: 'houses/steps'
    resources :tenders, only: [:new, :create], controller: 'trading/tenders'
  end
  resources :comments
  # resources :invoices do
  #   resources :payments
  # end

  # Static Pages
  # root "pages#landing"
  get "home", to: "insides#home", as: :user_root
  get "profil", to: "insides#profile", as: :profile
  get "pilih", to: "insides#choose", as: :choose
  post "/emailconfirmation", to: "insides#email", as: "email_confirmation"
  post "/subscribe", to: "insides#subscribe", as: "subscribe"
  post "/socialize", to: "insides#socialize", as: "socialize"
  get "/simulasi", to: "insides#simulation", as: "simulation"
  get '/change_locale/:locale', to: 'insides#change_locale', as: :change_locale

  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable"
  get "/500" => "errors#internal_server_error"

  namespace :admin do
    root "base#index"
    get 'subscribers', to: "base#subscribers", as: :subscribers
    put 'whitelisting', to: "base#whitelisting", as: :whitelisting
    post 'send_email', to: "base#send_email", as: :send_email
    get 'inbox', to: "base#inbox", as: :inbox
    get 'events', to: "analytics#events", as: :events_analytics
    get 'visits', to: "analytics#visits", as: :visits_analytics
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    resources :posts do
      member do
        put "remove_header"
      end
    end
    resources :documents do
      member do
        get "delete"
      end
    end
    resources :tenders, only: [:index, :edit, :update, :destroy]
    resources :bids, only: [:index, :edit, :update, :destroy]
    resources :houses, skip: [:show]
    resources :comments, skip: [:show]
  end

  # Vanity AB TESTING FRAMEWORK
  get '/vanity' =>'vanity#index'
  get '/vanity/participant/:id' => 'vanity#participant'
  post '/vanity/complete'
  post '/vanity/chooses'
  post '/vanity/reset'
  post '/vanity/add_participant'
  get '/vanity/image'


  get "/id/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'landing'

  resources :users, only: :show, path: '' do
    resources :tenders, only: :show, path: '', controller: 'trading/tenders'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  include WannabeBool::Attributes
  extend FriendlyId
  friendly_id :title, use: :slugged


  serialize :keywords, HashSerializer
  store_accessor :keywords, 
        :topic, :tags, :tags_text, :meta_description, :meta_image, :sticky
  attr_wannabe_bool :sticky

  has_many :comments, as: :commentable

  # Markdown
  before_save :mark_it_down!, :tags_as_array!

  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true

  # Pagination
  paginates_per 7

  # Relations
  belongs_to :user

  attr_accessor :delete_image, :image_id
  # before_validation :remove_attached_image

  # Scopes
  default_scope { order(created_at: :desc) }
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }

  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }
  scope :recent, -> { order('created_at DESC').limit(5) }
  scope :by_topic, ->(subject) { 
    where("posts.keywords->>'topic' = :words", words: "#{subject}") 
  }
  scope :by_tag, ->(words) { 
    #Not working, presummably because of the function
    # where("posts.keywords->>'tags' = :words", words: "#{words}") 
    # These one works
    where("keywords -> 'tags' ? :word", word: words)
  }  

  def remove_attached_image
    self.header.delete if delete_image == '1'
  end

private
  def mark_it_down!
    MarkdownWriter.update_html(self)
  end

  def tags_as_array!
    self.tags = self.tags_text.split(", ")
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_action :set_post, only: [
    :show,
    :edit,
    :update,
    :destroy, :remove_header
  ]


  def index
    @published_post_count = Post.published.count
    @draft_post_count = Post.drafted.count
    @posts = Post.published.page(params[:page]).per(50)
  end

  def show
  end

  def drafts
    @posts = Post.drafted.page(params[:page]).per(50)
  end

  def new
    @post = Post.new
    @sticky = "false"
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save 
      redirect_to admin_posts_path, notice: "New post published."
    else
      flash[:alert] = "Post not published."
      render :new
    end
  end

  def edit
    @sticky = @post.sticky
  end

  def update
    # @post.slug = nil
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: "Post successfully edited."
    else
      flash[:alert] = "The post was not edited."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: "The post has been deleted."
  end

  def remove_header
    if Cloudinary::Uploader.destroy(@post.header, type: :upload)
      @post.update_column(:header, nil)
      flash[:notice] = 'Header berhasil dihapuskan'
    else
      flash[:warning] = 'Header gagal dihapuskan'
    end
    redirect_to admin_posts_path
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
    :title,
    :content_md,
    :header,
    :delete_image,
    :meta_description,
    :meta_image,
    :image_id,
    :topic,
    :tags_text,
    :draft,
    :updated_at,
    :sticky
    )
  end


end

app/controllers/blog/comments_controller.rb
class Blog::CommentsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [
  #   :new, :edit, :create, :update
  # ]
  before_action :set_comment, only: [:edit]

  def new
  	@comment = Comment.new
    @parent = Comment.find(params[:parent_comment])
    @post = @parent.commentable
  end

  def edit
    # @comment = Comment.friendly.find(params[:id])
    @post = Post.friendly.find(params[:post_id])
  end

  def create
	  @comment = Comment.new(comment_params)
	  @comment.user = current_user || "Tamu"
    @post = Post.friendly.find(params[:post_id])
    @comment.commentable = @post

    if @comment.save
      ahoy.track "Posting Comment", title: "#{@comment.user} posted blog comments"
      redirect_to blog_post_path(@post)
      flash[:notice] = 'Komentar berhasil dibuat'
    else
      render :new
    end	
  end

  def update
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.friendly.find(params[:id])

    if @comment.update(comment_params)
      ahoy.track "Updating Comment", title: "Comment no.#{@comment.id} was edited"
      redirect_to blog_post_path(@post)
      flash[:notice] =  'Komentar berhasil dikoreksi'
    else
      render :edit
    end  	
  end


private
  def set_comment
  	@comment = Comment.friendly.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(
  	  :commentable, :commentable_id, :commentable_type, 
      :title, :body_md, :subject, :parent_id
  	)
  end	

end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [
    :index, :show, :find_posts, :discussion_room
  ]
  before_action :blog_layout
  before_action :tag_cloud#, only: [:posts, :show_post, :find_posts]

  def index
    @index = true
    @posts = Post.page(params[:page]).per(7)
        
    unless current_user.present? && current_user.admin?
      meta_events_tracker.event!(:visit, :blog, { page: 'blog page', referrer: request.referrer } )
    end
  end
  
  def show
    @post = Post.friendly.find(params[:id])

    unless current_user.present? && current_user.admin?
      meta_events_tracker.event!(:visit, :blogpost, { title: @post.title, category: 'blog', referrer: request.referrer } )
    end
  rescue  
    redirect_to root_path(subdomain: "blog")
  end

  def find_posts
    @index = true
    if params[:topic]
      @posts = Post.by_topic(params[:topic]).page(params[:page]).per(7)
    elsif params[:tag]
      @posts = Post.by_tag(params[:tag]).page(params[:page]).per(7)
    end
  end

  def discussion_room
  end


private
  def tag_cloud
    @all_posts = Post.all
    @topics = @all_posts.group_by{ |post| post.topic }
  end

  def blog_layout
    @blog_layout = true
    @recents = Post.recent
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  
  def cly_sm_header_options
  	{ :width => 300, :height => 150, :crop => :scale, format: :jpg }
  end
  def cly_lg_header_options
  	{ :width => 750, :height => 350, :crop => :scale, format: :jpg }
  end

end

app/views/blog/posts/_disqus.html.erb
<%= render partial: 'elements/disqus_script', locals: { identifier: @post.title } %>

app/views/blog/posts/_post.html.erb
<div class="post-box" id="post-<%= post.id %>">
	<% if request.variant.include? :phone %>
	  <%= cl_image_tag(post.meta_image, { :width => 300, :crop => :scale, type: 'upload' } ) %>
	<% else %>
	  <%= cl_image_tag(post.meta_image, { :width => 700, :crop => :scale, type: 'upload'}) %>
	<% end %>
  	<%= link_to blog_post_url(post.slug) do %>
	  <h3 class="ctitle"><%= post.title %></h3>
	<% end %>
	<p class=""><csmall>&nbsp;&nbsp;<%= post.updated_at.strftime("%Y, %B %-d") %></csmall> | <csmall2>Oleh: <%= post.user.name %></csmall2></p>
  
	<div class="post-truncate">
	  <%= sanitize truncate(post.content_html, length: 200, escape: false )%>
	</div>
	<p><%= link_to "Baca lebih lanjut", blog_post_path(post.slug) %></p>
	<div class="spacing"></div>

  <div class="post-footer">
  	<p>
		Kata Kunci: 
  	  <% unless post.tags.nil? %>
	  	<% post.tags.each do |tag| %>
	  	  <%= link_to blog_find_posts_path(tag: tag) do %>
	  	  	<span class="badge badge-info"><%= tag %></span>
	  	  <% end %>
	  	<% end %>
	  <% end %>
  	</p>
  </div>

  <% unless defined?(multiple) && multiple %>
  	<div id="disqus_thread"></div>	
  <% end %>

</div>

app/views/blog/posts/discussion_room.html.erb
<% meta title: "Ruang Diskusi", description: "Tempat kamu untuk bertanya sekaligus bertukar informasi" %>

<h3>Tempat diskusi dan tanya jawab</h3>
<hr>
<p>Kalau kamu ada pertanyaan, silahkan tulis di sini dan kami akan menjawabnya sebisa dan secepat mungkin</p>

<div id="disqus_thread"></div>
<%= render partial: 'elements/disqus_script', locals: { identifier: 'Ruang Diskusi' } %>

app/views/blog/posts/find_posts.html.erb
<% title("Pencarian Artikel") %>

<h3>Hasil Pencarian Artikel</h3>
<div>
<% @posts.each do |post| %>
  <%= render partial: 'elements/post', locals: { post: post, multiple: true } %>
  <div class="spacing"></div>
<% end %>
</div>

<div class="pagination-control text-center">
  <%= paginate @posts %>
</div>	

app/views/blog/posts/index.html.erb
<%
meta title: "Blog",
     description: "Blog yang membahas ekonomi & keuangan syariah serta kesuksesan dunia & akhirat",
     keywords: %w(ekonomi keuangan syariah islam kesuksesan kebahagiaan)
%>

<h4>Artikel Blog</h4><hr>
<div id="posts-list">
<% @posts.each do |post| %>
  <%= render partial: 'post', locals: { post: post, multiple: true } %>
  <div class="spacing"></div>
<% end %>
</div>

<div class="pagination-control text-center">
  <%= paginate @posts %>
</div>	

app/views/blog/posts/show.html.erb
<% meta title: @post.title, description: @post.meta_description,
     keywords: @post.tags %>

<% twitter card: 'summary_large_image', description: @post.meta_description,
          image: cl_image_path(@post.meta_image), title: @post.title %>

<% meta og: { 
        image: cl_image_path(@post.meta_image), title: @post.title, 
        description: @post.meta_description, locale: 'id_ID', 
        rich_attachment: true,
        url: "http://#{request.host + url_for(:page => params[:page]) }" 
        },
        fb: ENV["FB_APP_ID"] 
%>

<div class="col-md-10 col-md-offset-1 no-padding">
	<div class="outset-column no-select">
	<% if request.variant.include? :phone %>
	  <%= cl_image_tag(@post.meta_image, { :width => 300, :crop => :scale, type: 'upload', format: :jpg } ) %>
	<% else %>
	  <%= cl_image_tag(@post.meta_image, { :width => 1020, :crop => :scale, type: 'upload'}) %>
	<% end %>
	</div>
	<div class="single-column post-content no-select">
	  <p class="single-column post-content" style="margin-bottom: 0px;"><csmall>&nbsp;&nbsp;<%= @post.updated_at.strftime("%Y, %B %-d") %></csmall> | <csmall2>Oleh: <%= @post.user.name %></csmall2></p>
	  <h1 class="single-column post-content"><%=h @post.title %></h1>
	  
	  <div class="spacing"></div>
	  <div class="single-column post-content no-select">
	  	<%= @post.content_html.html_safe %>
	  </div>
	</div>
	<div class="single-column post-content">
		<h5>Share This Article!</h5>
		<%= social_share_button_tag(@post.title, url: blog_post_url(@post), desc: @post.meta_description) %>
	</div>
</div>