config/routes.rb
require 'api_constraints'
require 'subdomain'

Fustal::Application.routes.draw do
  wiki_root '/wiki'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { 
    :registrations => "registrations", :sessions => "sessions", 
    :passwords => "passwords", :omniauth_callbacks => "omniauth_callbacks" 
  }

  namespace :blog, path: '/blog' do
    get "find", to: "posts#find_posts", as: "find_posts"
    get "diskusi", to: "posts#discussion_room", as: "discussion"
    resources :posts do
    end
    get '' => "posts#index"
  end

# New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get "avatar"
      put "remove_avatar"
    end    
  end

  scope module: 'trading' do
    resources :tenders do
      member do
        get "discuss"
      end
      resources :bids
    end
  end

  resources :documents
  resources :houses do
    resources :steps, only: [:show, :update], controller: 'houses/steps'
    resources :tenders, only: [:new, :create], controller: 'trading/tenders'
  end
  resources :comments
  # resources :invoices do
  #   resources :payments
  # end

  # Static Pages
  # root "pages#landing"
  get "home", to: "insides#home", as: :user_root
  get "profil", to: "insides#profile", as: :profile
  get "pilih", to: "insides#choose", as: :choose
  post "/emailconfirmation", to: "insides#email", as: "email_confirmation"
  post "/subscribe", to: "insides#subscribe", as: "subscribe"
  post "/socialize", to: "insides#socialize", as: "socialize"
  get "/simulasi", to: "insides#simulation", as: "simulation"
  get '/change_locale/:locale', to: 'insides#change_locale', as: :change_locale

  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable"
  get "/500" => "errors#internal_server_error"

  namespace :admin do
    root "base#index"
    get 'subscribers', to: "base#subscribers", as: :subscribers
    put 'whitelisting', to: "base#whitelisting", as: :whitelisting
    post 'send_email', to: "base#send_email", as: :send_email
    get 'inbox', to: "base#inbox", as: :inbox
    get 'events', to: "analytics#events", as: :events_analytics
    get 'visits', to: "analytics#visits", as: :visits_analytics
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    resources :posts do
      member do
        put "remove_header"
      end
    end
    resources :documents do
      member do
        get "delete"
      end
    end
    resources :tenders, only: [:index, :edit, :update, :destroy]
    resources :bids, only: [:index, :edit, :update, :destroy]
    resources :houses, skip: [:show]
    resources :comments, skip: [:show]
  end

  # Vanity AB TESTING FRAMEWORK
  get '/vanity' =>'vanity#index'
  get '/vanity/participant/:id' => 'vanity#participant'
  post '/vanity/complete'
  post '/vanity/chooses'
  post '/vanity/reset'
  post '/vanity/add_participant'
  get '/vanity/image'


  get "/id/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'landing'

  resources :users, only: :show, path: '' do
    resources :tenders, only: :show, path: '', controller: 'trading/tenders'
  end

end

app/views/elements/_authorship_credit.html.erb
<div>
	<p><small>
		Icons made by 
		<a href="http://www.flaticon.com/authors/freepik" title="Freepik">
			Freepik
		</a> from 
		<a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>
		is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>
	</small></p>
</div>

app/views/elements/_blankslate.html.erb
<div class="blankslate">
	<div class="spacious">
		<h3><%= heading %></h3>
		<p><%= explanation %></p>
		<%= link_to anchor, destination, class: "btn btn-lg btn-primary"  %>
	</div>
</div>

app/views/elements/_button_double.html.erb
<a href="#" class="btn btn-primary inverse">
    <i class="fa fa-android fa-3x pull-left"></i>
    <span>Download for</span><br>
    <b>Android</b>
</a>

app/views/elements/_client_simulation.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
  <center>
    <h5 class="coral">Formula simulasi dapat berubah sewaktu-waktu</h5>
    <%= simple_form_for(:simulation, { url: simulation_path, method: 'get', remote: true, html: { class: 'form-vertical' }, wrapper: :vertical_form }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :tangible, as: :select, collection: [ "Rumah", "Apartemen" ], prompt: "pilih", label: "Jenis Properti", required: true %>

      <%= f.input :maturity, as: :integer, input_html: { value: '5', min: '3', max: '10',step: '1' }, label: "Lama Syirkah (Tahun)", required: true %>

      <%= f.input :contribution, as: :integer, input_html: { value: '20', min: '20', max: '80',step: '5' }, label: "Modal Kamu (%)", hint: 'Dibandingkan dengan harga rumah', required: true %>

      <%= f.input :price, input_html: { class: "slide-input", :data => {'slider-min'=> "0", 'slider-max'=> "950000000", 'slider-value'=> "100000000", 'slider-step'=> "10000000"} }, label: "Harga", required: true %>      
    </div>

    <div class="form-group">
      <div class="col-sm-2 col-xs-1"></div>
      <label for="amount" class="col-sm-4 col-xs-5 control-label">Harga (Rp): </label>
      <!-- <span class="help-text">Please choose your amount</span> -->
      <div class="col-sm-4 col-xs-5">
        <p id="amount-inputSliderVal" class="price lead">100</p>
        <span class="price"> jt</span>
      </div>
      <div class="col-sm-2 col-xs-1"></div>
    </div>

    <div class="form-actions">
      <%= button_tag "Hitung", class: "btn btn-lg btn-primary btn-round-lg", data: {disable_with: "<i class='fa fa-spinner fa-pulse'>
      </i> Sedang dihitung..."}  %>
    </div>
  <% end %>

  </center>
</div>


<script type="text/javascript">

$(function() {

  var inputSliderValue = 0;
  var humanizer = 1000000;

  function changeValue(){
    var currentSliderValue = inputSliderValue / humanizer;
    $( "#amount-inputSliderVal" ).text( currentSliderValue );
  }

  $(".slide-input").slider();
  $("#simulation_price").on("slide", function(slideEvt) {
    inputSliderValue = slideEvt.value;
    changeValue();
  })
});
</script>

app/views/elements/_contact.html.erb
<div class="modal-header modal-header-primary">
  <h3>Kontak</h3>
</div>
<div class="modal-body primary-background">
  <center>
    <h3 class="white media-heading"><%= "Kirim pesan kepada kami" %></h3>
	  <%= render 'elements/form_contact' %>
  </center>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-warning pull-left" data-dismiss="modal">Batalkan</button>
</div>

app/views/elements/_contact_modal.html.erb
<script type="text/javascript">
  document.getElementById("BT1").addEventListener("click", function(){
      $("#simulation").hide();
      $("#explanation").show();
  });
  document.getElementById("BT2").addEventListener("click", function(){
      $("#explanation").hide();
      $("#simulation").show();
      $("#BT1").show();
  });    
</script>

app/views/elements/_direct_photo_upload.html.erb
<div id="direct_upload">
  <p>Format yang diterima adalah .jpg atau .png maksimal 1 MB. Bisa dengan mengklik tombol 'Unggah' atau dengan drag dan drop ke dalam area bergaris</p>
    <% unless defined?(edit) && edit %>
    <div class="form_line">
      <%= f.label :image_id, "Foto:" %>
      <div class="form_controls">
        <div class="upload_button_holder">
          <%= link_to("Unggah", "#", :class => "upload_button") %>
          <%= f.cl_image_upload :image_id, upload_preset: "fdh747hl", :return_delete_token=>true, class: "cloudinary-fileupload" %>
        </div>
        <span class="status"></span>
      </div>
    </div>
    <% end %>
    <div class="form_line">
      <div class="form_controls">
        <div class="preview"></div>
      </div>
    </div>
    <%= f.hidden_field :avatar, class: "avatar_field" %>
</div>


<script>
  $(document).ready(function() {
    // Cloudinary jQuery integration library uses jQuery File Upload widget
    // (see http://blueimp.github.io/jQuery-File-Upload/).
    // Any file input field with cloudinary-fileupload class is automatically
    // wrapped using the File Upload widget and configured for Cloudinary uploads.
    // You can further customize the configuration using .fileupload method
    // as we do below.
    $(".cloudinary-fileupload")
      .cloudinary_fileupload({ 
        // Uncomment the following lines to enable client side image resizing and valiation.
        // Make sure cloudinary/processing is included the js file
        //disableImageResize: false,
        //imageMaxWidth: 800,
        //imageMaxHeight: 600,
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
        maxFileSize: 1000000, // 1MB
        dropZone: "#direct_upload",
        start: function (e) {
          $(".status").text("Starting upload...");
        },
        progress: function (e, data) {
          $(".status").text("Uploading... " + Math.round((data.loaded * 100.0) / data.total) + "%");
        },
        // done: function (e, data) {
        //   $(".status").text("File berhasil diunggah, silahkan tekan Simpan");
        // },        
        fail: function (e, data) {
          $(".status").text("Upload failed");
        }
      })
      .off("cloudinarydone").on("cloudinarydone", function (e, data) {
        NProgress.done(true);
        $(".status").text("File berhasil diunggah, silahkan tekan Simpan");
        $(".avatar_field").val(data.result.public_id);
        // $(".status").text("");
        var preview = $(".preview").html('');
        $.cloudinary.image(data.result.public_id, {
          format: 'jpg', width: 50, height: 50, crop: "fit"
        }).appendTo(preview);

        // $('<a/>').
        //   addClass('delete_by_token').
        //   attr({href: '#'}).
        //   data({delete_token: data.result.delete_token}).
        //   html('&times;').
        //   appendTo(preview).
        //   click(function(e) {
        //     e.preventDefault();
        //     $.cloudinary.delete_by_token($(this).data('delete_token')).done(function(){
        //       $('.preview').html('');
        //       $('#info').html('');
        //       $("#photo_bytes").val('');
        //       $('input[name="user[image_id]"]').remove();
        //     }).fail(function() {
        //       $('.status').text("Cannot delete image");
        //   });
        // });
        // view_upload_details(data.result);
      });
    });
    
    // function view_upload_details(upload) {
    //   // Build an html table out of the upload object
    //   var rows = [];
    //   $.each(upload, function(k,v){
    //     rows.push(
    //       $("<tr>")
    //         .append($("<td>").text(k))
    //         .append($("<td>").text(JSON.stringify(v))));
    //   });
    //   $("#info").html(
    //     $("<div class=\"upload_details\">")
    //       .append("<h2>Upload metadata:</h2>")
    //       .append($("<table>").append(rows)));
    }
}
</script>

app/views/elements/_disqus_script.html.erb
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */

    var disqus_shortname = '<%= Naming::DISQUS_SHORTNAME %>';
    var disqus_identifier = '<%= identifier %>';
    var disqus_url = '<%= request.original_url %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/elements/_form_contact.html.erb
<%= form_tag email_confirmation_path, method: 'post', html: {role: "form"} do %>

<div class="form-group">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= text_field_tag :name, '', placeholder: "Nama kamu", class: "form-control", required: true %>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= text_field_tag :email, '', placeholder: "Alamat email kamu", class: "form-control", required: true %>
    </div>        
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-xs-12">
      <%= text_area_tag :message, '', placeholder: "Isi pesan", rows: 10, class: "form-control", required: true %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 padded">
    <%= submit_tag 'Kirim', class: 'btn btn-md btn-success' %>
  </div>
</div>
<% end %>

app/views/elements/_house_item_view.html.erb
<p>Punya rumah pilihan sendiri? Silahkan daftarkan terlebih dahulu</p>
<p><%= link_to "Daftarkan Rumah", houses_path(build: 'true'), method: :post, class: "btn btn-md btn-inverse" %></p><br>

<div id="property-listings">
<% houses.each do |house| %>
  <div class="brdr bgc-fff box-shad btm-mrg-20 property-listing">
    <div class="media">
      <%= render_house_display_for_tender(house, 'col-xs-5 col-sm-4') %>

      <!-- <div class="clearfix visible-sm"></div> -->
      <div class="col-xs-7 col-sm-8 media-outer-right">
        <div class="media-body fnt-smaller">
          <a href="#" target="_parent"></a>

          <h4 class="media-heading">
            <%= idr_money house.price %> 
            <small class="pull-right">
               <%= sale_label(house) %> <%= rent_label(house) %> <%= vacant_label(house) %>            
            </small>
          </h4>

          <p><%= house.address %></p>
          <ul class="list-inline mrg-0 clr-535353">
            <li><%= house.lot_size %>m2</li>
            <li style="list-style: none">|</li>
            <li> <span class="hidden-xs hidden-sm"><%= house.bedrooms %> Kamar tidur</span> <i class="fa fa-bed visible-xs visible-sm"> <%= house.bedrooms %></i></li>
            <li style="list-style: none">|</li>
            <li><span class="hidden-xs hidden-sm"><%= house.bathrooms %> Kamar mandi</span><i class="fa fa-tint visible-xs visible-sm"> <%= house.bathrooms %></i></li>
          </ul>

          <p>
            <span class="lggrey pull-left hidden-xs">
              <small class="">
                Pendaftaran: <strong><%= house.form_step %></strong> <sup><strong>.</strong></sup> Status: <strong><%= house.state %></strong>
              </small>
            </span>
            <%= link_to "Pilih", new_house_tender_path(house), class: "btn btn-xs btn-primary pull-right pick-house" %>
          </p>
        </div>
      </div>
    </div>
  </div><!-- End Listing-->  
<% end %>
</div>

app/views/elements/_house_list.html.erb
<div class="wp-block-item property-list">
  <div class="body">
    <div class="wp-block-img">
      <%= link_to house_path(house) do %>
          <%= render_house_display(house, '') %>
      <% end %>
    </div>
    <div class="wp-block-content">
      <h5><%= house.address %>  <small><%= house.city %></small></h5>
      <small class="lggrey">
    	  Pendaftaran: <strong><%= house.form_step %></strong> <sup><strong>.</strong></sup> Status: <strong><%= house.state %></strong>
      </small> <br>
      <small>
         <%= sale_label(house) %> <%= rent_label(house) %> <%= vacant_label(house) %>
      </small><br>
      <span class="pull-left">
          <ul class="social-links">
              <li><%= edit_link(house) %></li>
              <li><%= show_link(house) %></li>
              <li>
                  <%= link_to house_path(house), method: :delete, data: {confirm: 'Kamu yakin mau melanjutkan?', object: 'Penghapusan rumah', toggle: 'tooltip', placement: 'top', original_title: 'Hapus'} do %>
                      <i class="fa fa-trash"></i> <span class="hidden-xs"> Hapus</span>
                  <% end %>
              </li>
          </ul>                     
      </span>
      <span class="pull-right coral">
          <strong><%= idr_money(house.price.to_i) %></strong>
      </span>
    </div>
  </div>
</div>

app/views/elements/_mixpanel_script.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("24c615e2644b3bd30487ba632abd7ace");</script><!-- end Mixpanel -->

app/views/elements/_small_modal.html.erb
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2">Modal title</h4>
      </div>
      <div class="modal-body">
        <h4>Text in a modal</h4>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
        <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>

    </div>
  </div>
</div>

app/views/elements/_tip.html.erb
<i class="fa fa-question-circle fa-lg pop-helper" data-container="body" data-toggle="popover" data-placement="top" title="Other Prep" data-content="<%= credibility_popover_text %>" data-original-title=""></i>