config/routes.rb
require 'api_constraints'
require 'subdomain'

Fustal::Application.routes.draw do
  wiki_root '/wiki'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { 
    :registrations => "registrations", :sessions => "sessions", 
    :passwords => "passwords", :omniauth_callbacks => "omniauth_callbacks" 
  }

  namespace :blog, path: '/blog' do
    get "find", to: "posts#find_posts", as: "find_posts"
    get "diskusi", to: "posts#discussion_room", as: "discussion"
    resources :posts do
    end
    get '' => "posts#index"
  end

# New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get "avatar"
      put "remove_avatar"
    end    
  end

  scope module: 'trading' do
    resources :tenders do
      member do
        get "discuss"
      end
      resources :bids
    end
  end

  resources :documents
  resources :houses do
    resources :steps, only: [:show, :update], controller: 'houses/steps'
    resources :tenders, only: [:new, :create], controller: 'trading/tenders'
  end
  resources :comments
  # resources :invoices do
  #   resources :payments
  # end

  # Static Pages
  # root "pages#landing"
  get "home", to: "insides#home", as: :user_root
  get "profil", to: "insides#profile", as: :profile
  get "pilih", to: "insides#choose", as: :choose
  post "/emailconfirmation", to: "insides#email", as: "email_confirmation"
  post "/subscribe", to: "insides#subscribe", as: "subscribe"
  post "/socialize", to: "insides#socialize", as: "socialize"
  get "/simulasi", to: "insides#simulation", as: "simulation"
  get '/change_locale/:locale', to: 'insides#change_locale', as: :change_locale

  get "/404" => "errors#not_found"
  get "/422" => "errors#unprocessable"
  get "/500" => "errors#internal_server_error"

  namespace :admin do
    root "base#index"
    get 'subscribers', to: "base#subscribers", as: :subscribers
    put 'whitelisting', to: "base#whitelisting", as: :whitelisting
    post 'send_email', to: "base#send_email", as: :send_email
    get 'inbox', to: "base#inbox", as: :inbox
    get 'events', to: "analytics#events", as: :events_analytics
    get 'visits', to: "analytics#visits", as: :visits_analytics
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    resources :posts do
      member do
        put "remove_header"
      end
    end
    resources :documents do
      member do
        get "delete"
      end
    end
    resources :tenders, only: [:index, :edit, :update, :destroy]
    resources :bids, only: [:index, :edit, :update, :destroy]
    resources :houses, skip: [:show]
    resources :comments, skip: [:show]
  end

  # Vanity AB TESTING FRAMEWORK
  get '/vanity' =>'vanity#index'
  get '/vanity/participant/:id' => 'vanity#participant'
  post '/vanity/complete'
  post '/vanity/chooses'
  post '/vanity/reset'
  post '/vanity/add_participant'
  get '/vanity/image'


  get "/id/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'landing'

  resources :users, only: :show, path: '' do
    resources :tenders, only: :show, path: '', controller: 'trading/tenders'
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  include WannabeBool::Attributes
  include RefreshSlug
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged  
  protokoll :ticker, :pattern => "DOC%y####%m"
  belongs_to :owner, polymorphic: true
  
  attr_accessor :image_id
  store_accessor :details, 
  					:public_id, :bytes, :state, :doc_type,
  					:checked, :flagged
  
  attr_wannabe_bool :checked, :flagged

  # Pagination
  paginates_per 30

  cattr_accessor :categories do
    %w(identitas penghasilan pengeluaran kepemilikan)
  end
  
  # validates :public_id, :presence => true
  
  before_create :set_default
  after_create :refresh_friendly_id!
  
  scope :verifieds, -> { 
    where("documents.details->>'state' = :state", state: "verified") 
  }    
  scope :by_types, ->(doc_type) { 
    where("documents.details->>'doc_type' = :type", type: doc_type) 
  }
  scope :identities, -> { 
    where("documents.details->>'doc_type' = :type", type: "identitas") 
  }
  scope :incomes, -> { 
    where("documents.details->>'doc_type' = :type", type: "bukti penghasilan") 
  }
  scope :expenses, -> { 
    where("documents.details->>'doc_type' = :type", type: "bukti pengeluaran") 
  }
  scope :collaterals, -> { 
    where("documents.details->>'doc_type' = :type", type: "bukti kepemilikan") 
  }
  def transitioning!
    # if self.checked? &&  self.flagged?
    #   self.state_machine.transition_to!(:dropped)
    # else
    #   if self.checked?
    #     self.state_machine.transition_to!(:verified)
    #   elsif self.flagged?
    #     self.state_machine.transition_to!(:flagged)
    #   elsif !self.checked? &&  !self.flagged?
    #     self.state_machine.transition_to!(:uploaded)
    #   end
    # end
  end

  cattr_accessor :identity_proofs do
    ["KTP", "SIM," "Passport", "NPWP", "Kartu Keluarga"]
  end
  cattr_accessor :earning_proofs do
    ["Slip Gaji", "Surat Keterangan Masa Kerja", 
      "Laporan Keuangan Bisnis", "Akta Perusahaan", "SIUP", "TDP",
      "Surat Izin Praktek", "Sertifikat Profesi"]
  end
  cattr_accessor :expense_proofs do
    ["Buku Tabungan", "Bukti Bayar Listrik", "Lain-lain"]
  end
  cattr_accessor :collateral_proofs do
    ["BPKB", "Girik", "SHGB", "SHGB", "SHM"]
  end      
  # def identity_proof
  #   ["KTP", "SIM", "Passport", "NPWP", "Kartu Keluarga"]
  # end

  def earning_proof
  end

  def expense_proof
  end

  def collateral_proof
    
  end

private
  def slug_candidates
    [ :ticker ]
  end

  def set_default
    self.checked = 'no'
    self.flagged = 'no'
    self.state = 'new'
    self.category = check_category
  end

  def check_category
    if self.identity_proofs.include? self.doc_type
      return 'identitas'
    elsif  self.earning_proofs.include? self.doc_type
      return 'penghasilan'
    elsif  self.expense_proofs.include? self.doc_type
      return 'pengeluaran'
    elsif  self.collateral_proofs.include? self.doc_type
      return 'kepemilikan'
    end
  end

end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < Admin::BaseController
  before_action :set_document, only: [:show, :edit, :update]

  def index
    @admin = true
    @documents = Document.order(:created_at).page params[:page]
  end

  def show
    @admin = true
  end

  def update
    if @document.update(document_params)
      @document.transitioning!
      flash[:notice] = 'Dokumen berhasil diproses'
      redirect_to admin_documents_path 
    else
      flash[:warning] = 'Dokumen gagal diproses'
      render :index
    end    
  end

  private

  def set_document
    @document = Document.friendly.find(params[:id])
  end

  def document_params
    params.require(:document).permit(
    :checked,
    :flagged,
    :public_id
    )
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :inside_app
  before_action :set_document, only: [:show, :edit, :update, :delete, :destroy]

  def show
    # @pic = Cloudinary::Api.resource(@document.public_id)
  end

  def new
  	@document = Document.new
  end

  def create
  	@document = Document.new(document_params)
    @document.assign_attributes(owner: current_user)

  	if @document.save
	    redirect_to user_path(current_user)
	    flash[:notice] = 'Dokumen berhasil disimpan'
      meta_events_tracker.event!(:user, :uploaded_document, { document_type: @document.doc_type, category: @document.category })
	  else
		  render :new
	  end
  end

  def edit
    @category = @document.category
  end

  def update
  end

  def destroy
    # Cloudinary::Api.delete_resources([@document.public_id], type: :private)
    Cloudinary::Uploader.destroy(@document.public_id, type: :private)
  	@document.destroy
    
    # ahoy.track "Document Destroyed", 
    #   title: "#{@document.owner.name} - #{@document.doc_type}", 
    #   category: "Document", important: "Client"
    
    flash[:notice] = 'Dokumen berhasil dihapus'
    redirect_to user_path(current_user)
  end

  def delete
  end

private
  def set_document
  	@document = Document.friendly.find(params[:id])
  	# @document = Document.find(params[:id])
  end

  def document_params
  	params.require(:document).permit(
  	  :name, :category, :slug, :image_id, :doc_type,
  	  :bytes, :public_id,
  	  :owner_type, :owner_id, :owner
  	)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper


	def document_checklist(doc)
		if doc.check_if_uploaded?
			content_tag(:span, "v", class: "badge badge-success", 
				:"data-toggle" => "tooltip", :"data-placement" => "left",
				:"title" => "sudah")
		else
			content_tag(:span, " ", class: "badge", 
				:"data-toggle" => "tooltip", :"data-placement" => "left",
				:"title" => "belum")			
		end
	end

	def docs_per_category(category)
		if category == 'identitas'
			return identity_docs
		elsif category == 'penghasilan'
			return earning_docs
		elsif category == 'pengeluaran'
			return expense_docs
		elsif category == 'kepemilikan'
			return collateral_docs
		end
	end

end

app/views/documents/_backup_form.html.erb
<!-- Ok for jpg and png, but not for pdf -->

<%= form_for @document, role: "form" do |f| %>

  <%= f.label :name, label: "Nama Dokumen" %>
  <%= f.text_field :name  %>
  
  <%= f.attachinary_file_field :proofs %>  
  <%= f.label :category, label: "Jenis Dokumen" %>
  <%= f.text_field :category %>
  <%= f.submit "Simpan", class: "btn btn-primary" %>
    <button class='btn btn-outlined btn-black'>
      <i class='fa fa-plus-square'></i> Simpan
    </button>
<% end %>

<script type="text/javascript">  
  document.getElementById("upload_widget_opener").addEventListener("click", function() {

    cloudinary.openUploadWidget({ cloud_name: 'instilla', upload_preset: 'o9z2o3rl'}, 
      function(error, result) { console.log(error, result) });

  }, false);
</script>

app/views/documents/_doc_list.html.erb
<div class="col-md-10 col-md-offset-1" id="documents-view">
  <ul class="document-listing" id="bid-list" style="padding-left: 0px;">
    <% if documents.present? %>  
      <% documents.each_with_index do |document, index| %>
        <li class="bid-item">
          <div class="row listing-container">
          <div class="col-md-4 left-detail">
            <div class="s-grid-inner">
              <span class="category"><%= document.category %></span>
            </div>
          </div>
          <div class="col-md-8">
            <div class="s-grid-outer">
              <div class="s-grid-inner">
                <div class="col-xs-8" style="padding-left: 0px;">
                  <span class="doc_type"><%= document.doc_type %></span>
                  <p class="listing-data">Last modified was <%= time_ago_in_words(document.updated_at) %> ago</p>
                </div>
                <div class="col-xs-4 listing-actions float-right">
                  <strong><%= document.state %></strong>
                  <p class="listing-data">Status</p>
                </div>              
              </div>
            </div>
          </div>
          </div>  
        </li>
      <% end %>
    <% else %>
      <li class="centered grey">
        <h4><%= "Belum ada berkas" %></h4>
        <h1><i class="ion ion-compose"></i></h1>
        <p></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/documents/_document.html.erb
<% if defined?(zoomed) && zoomed %>
<div class="panel panel-default zoomed" id="panel-image">
<% else %>
<div class="panel panel-default" id="panel-image">
<% end %>
    <div class="panel-heading">
        <small><%= document.ticker %></small>
    </div>
    <div class="panel-image hide-panel-body">
        <% if defined?(thumbnail) && thumbnail %>
		    <%= cl_image_tag(document.public_id, cloudinary_thumbnail_options ) %>
        <% elsif defined?(zoomed) && zoomed %>
            <%= cl_image_tag(document.public_id, cloudinary_zoomed_options ) %>
        <% end %>
    </div>
    <div class="panel-footer text-center">
        <span class="badge"><%= document.state %></span>
        <% if @admin %>
            <%= link_to cl_private_download_url("my_private_image", :jpg, :attachment => true) do %>
                <span class="glyphicon glyphicon-download"></span>
            <% end %>
            <%= link_to admin_document_path(document), remote: true do %>
                <span class="glyphicon glyphicon-zoom-in"></span>
            <% end %>
            <%= link_to edit_document_path(document) do %>
                <span class="glyphicon glyphicon-pencil"></span>
            <% end %>            
            <% if defined?(checking) && checking %>
                <%= render 'admin/documents/checking' %>
            <% end %>
        <% else %>
            <% unless defined?(zoomed) && zoomed %>
                <%= link_to document_path(document), remote: true, class: 'zoom-link' do %>
                    <span class="glyphicon glyphicon-zoom-in"></span>
                <% end %>
            <% end %>
        <% end %>
        <% unless defined?(zoomed) && zoomed %>
            <%= link_to document_path(document), method: :delete, data: {confirm: 'Kamu yakin mau melanjutkan?', object: 'Penghapusan dokumen'}, class: 'delete-link' do %>
                <span class="glyphicon glyphicon-trash reset-link"></span>
            <% end %>
        <% end %>
    </div>
</div>

app/views/documents/_documents.html.erb
<h2>Pengelolaan Berkas</h2>

<% unless @documents.blank? %>
  <div class="col-xs-12">
    <% @documents.each do |document| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <%= render partial: "documents/document", locals: { document: document, thumbnail: true } %>
      </div>
    <% end %>
  </div>  
<% else %>
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
    <div class="spacing"></div>
    <h5 class="centered">Belum ada </h5>
  </div>

<% end %>

app/views/documents/_form.html.erb
<% meta title: "Unggah Berkas" %>

<div id="direct_upload">
  <p>Format yang diterima adalah .jpg, .png, dan .pdf. Bisa dengan mengklik tombol 'Pilih File' atau dengan drag dan drop ke dalam area bergaris</p>
  <%= form_for(@document) do |f| %>
    <% if defined?(edit) && edit %>
      <div class="form_line">
        <%= f.label :image_id, "Berkas" %>
        <div class="form_controls">
          <%= render partial: "documents/document", locals: { document: @document, thumbnail: true } %>
        </div>
      </div>      
    <% else %>
      <div class="form_line centered" style="margin-top: 35px;">
        <%= f.label :image_id, "Berkas" %>
        <div class="form_controls">
          <div class="upload_button_holder">
            <%= link_to("Pilih File", "#", :class => "upload_button btn-lg") %>
            <%= f.cl_image_upload :image_id, upload_preset: "ftisnjlh", :return_delete_token=>true, class: "cloudinary-fileupload" %>
          </div>
          <span class="status"></span>
        </div>
      </div>
    <% end %>

    <div class="tabbable-panel">
      <div class="tabbable-line">
        <div class="tab-content centered" style="margin-top: 35px;">
          <div class="tab-pane active" id="identity">
            <div class="form_line centered">
              <p><%= f.label :doc_type, "Jenis Berkas" %></p>
              <p>
                <%= f.select :doc_type, grouped_options_for_select(grouped_docs), prompt: "Pilih", required: true %>
              </p>
            </div>  
          </div>
        </div>
      </div>
    </div>

    <div class="form_line">
      <div class="form_controls">
        <div class="preview"></div>
      </div>
    </div>
    <div class="spacing"></div>
    <div class="form_line centered">
      <div class="form_controls">
        <%= f.submit "Simpan", class: "btn btn-success btn-lg" %>
        <% if @error %><span class="error"><%= @error %></span><% end %>
      </div>
    </div>
    <%= f.hidden_field :bytes %>
    <%= f.hidden_field :public_id %>
  <% end %>
</div>  


<div id="info"></div>


<% unless Rails.env.test? %>
  <script>
    $(document).ready(function() {
      // Cloudinary jQuery integration library uses jQuery File Upload widget
      // (see http://blueimp.github.io/jQuery-File-Upload/).
      // Any file input field with cloudinary-fileupload class is automatically
      // wrapped using the File Upload widget and configured for Cloudinary uploads.
      // You can further customize the configuration using .fileupload method
      // as we do below.
      $(".cloudinary-fileupload")
        .cloudinary_fileupload({ 
          // Uncomment the following lines to enable client side image resizing and valiation.
          // Make sure cloudinary/processing is included the js file
          //disableImageResize: false,
          //imageMaxWidth: 800,
          //imageMaxHeight: 600,
          //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
          //maxFileSize: 20000000, // 20MB
          dropZone: "#direct_upload",
          start: function (e) {
            $(".status").text("Starting upload...");
          },
          progress: function (e, data) {
            $(".status").text("Uploading... " + Math.round((data.loaded * 100.0) / data.total) + "%");
          },
          fail: function (e, data) {
            $(".status").text("Upload failed");
          }
        })
        .off("cloudinarydone").on("cloudinarydone", function (e, data) {
          NProgress.done(true);
          $("#document_bytes").val(data.result.bytes);
          $("#document_public_id").val(data.result.public_id);
          $(".status").text("");
          var preview = $(".preview").html('');
          $.cloudinary.image(data.result.public_id, {
            format: 'jpg', width: 50, height: 50, crop: "fit"
          }).appendTo(preview);

          $('<a/>').
            addClass('delete_by_token').
            attr({href: '#'}).
            data({delete_token: data.result.delete_token}).
            html('&times;').
            appendTo(preview).
            click(function(e) {
              e.preventDefault();
              $.cloudinary.delete_by_token($(this).data('delete_token')).done(function(){
                $('.preview').html('');
                $('#info').html('');
                $("#photo_bytes").val('');
                $('input[name="document[image_id]"]').remove();
              }).fail(function() {
                $('.status').text("Cannot delete image");
            });
          });
          view_upload_details(data.result);
        });
      });
      
      function view_upload_details(upload) {
        // Build an html table out of the upload object
        var rows = [];
        $.each(upload, function(k,v){
          rows.push(
            $("<tr>")
              .append($("<td>").text(k))
              .append($("<td>").text(JSON.stringify(v))));
        });
        $("#info").html(
          $("<div class=\"upload_details\">")
            .append("<h2>Upload metadata:</h2>")
            .append($("<table>").append(rows)));
      }
  </script>
<% end %>

app/views/documents/_form2.html.erb
<!-- Success!! uploading pdf but converted to png right away, stored in location -->

<%= form_for @document, role: "form" do |f| %>

  <%= f.label :nama_dokumen %>
  <%= f.text_field :name  %>
  
  <%= f.label :lokasi %>
  <%= f.text_field :location, class: "image_public_id"  %>
  
  <%= cl_image_upload_tag(:image_id, format: :png) %>

  <div class="preview">
  </div>


  <%= f.label :category, label: "Jenis Dokumen" %>
  <%= f.text_field :category %>
  <%= f.submit "Simpan", class: "btn btn-primary" %>
          

<% end %>

app/views/documents/_upload_doc.html.erb
<div class="modal-header modal-header-primary coral-background">
  <h3>Permintaan Pendanaan</h3>
</div>
<div class="modal-body">
  <div class="card">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#identity" aria-controls="identity" role="tab" data-toggle="tab">Identitas</a></li>
        <li role="presentation"><a href="#earning" aria-controls="earning" role="tab" data-toggle="tab">Penghasilan</a></li>
        <li role="presentation"><a href="#expense" aria-controls="expense" role="tab" data-toggle="tab">Pengeluaran</a></li>
        <li role="presentation"><a href="#collateral" aria-controls="collateral" role="tab" data-toggle="tab">Kepemilikan</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="identity">
        <%= render partial: 'form', locals: { category: "identitas", types: identity_docs } %>
      </div>
      <div role="tabpanel" class="tab-pane" id="earning">
      	<%= render partial: 'form', locals: { category: "penghasilan", types: earning_docs } %>
      </div>
      <div role="tabpanel" class="tab-pane" id="expense">
      	<%= render partial: 'form', locals: { category: "pengeluaran", types: expense_docs } %>
      </div>
      <div role="tabpanel" class="tab-pane" id="collateral">
      	<%= render partial: 'form', locals: { category: "kepemilikan", types: collateral_docs } %>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-warning pull-left" data-dismiss="modal">Batalkan</button>
</div>

app/views/documents/delete.js.erb
$("#inner-main-modal").html("<%= j (render partial: 'elements/delete_prompt', 
		locals: { object: @document, category: 'dokumen' }) %>")
$("#main-modal").modal("show")

app/views/documents/edit.html.erb
<% title("Edit Dokumen") %>

  <div class="portlet portlet-bordered">
  	<%= render partial: 'documents/form', locals: { category: @category, types: all_docs } %>

  	<strong>
  		<%= link_to "Kembali ke Profil", user_path(current_user) %> |
  		<%= link_to "Kembali ke Beranda", user_root_path %>
  	</strong>
  	
  </div>

app/views/documents/new.js.erb
$("#inner-home-modal").html("<%= j (render partial: 'documents/upload_doc',
  	locals: { heading: 'Unggah Dokumen'} ) %>")
$("#home-modal").modal("show")

app/views/documents/show.js.erb
$("#inner-user-modal").html("<%= j (render partial: 'documents/document', locals: { document: @document, zoomed: true }) %>")
$("#user-modal").modal("show")